name: absensi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1
 
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  UI
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.5

# Format
  intl: ^0.18.0

#  Assets
  flutter_svg: ^2.0.9

#  Admob
  google_mobile_ads: ^4.0.0

#  Firebase
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
  firebase_database: ^10.3.8
  firebase_auth: ^4.15.3
  flutter_easyloading: ^3.0.5
  currency_text_input_formatter: ^2.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Home.svg
    - assets/Profile.svg
    - assets/Search.svg
    - assets/Calendar.svg
    - assets/u_money-stack.svg
    - assets/Fingerprint.svg
    - assets/ClockClockwise.svg
    - assets/Background.png
    - assets/man_computer.png
    - assets/icon_call.svg
    - assets/icon_email.svg
    - assets/icon_logout.svg
    - assets/icon_password.svg
    - assets/icon_person.svg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600